name: china-ir
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - statsmodels
      - linearmodels
      - pycountry
      - plotnine
      - pyarrow
      - pytest
      - black
      - flake8
      - isort
      - pre-commit
